### ISSUE TITLE
Add Possibility to Provide Mask for Ripple

### ISSUE THREAD

**Issue by OFmarting** [infotech-group/android-drawable-dsl#10]
Hi,
Currently the `content` and the `mask` Arguments use the same Drawable when creating a [RippleDrawable](https://github.com/infotech-group/android-drawable-dsl/blob/master/src/main/kotlin/group/infotech/drawable/dsl/drawable-dsl.kt#L34). There should be the possibility to provide a separate Drawable for the Mask.

**Comment by meoyawn** [comment]
Hey! you can call `rippleDrawable` with your own arguments, like this:

https://github.com/infotech-group/android-drawable-dsl/blob/3672bd8237713e0b1b21d7f48a26a85d4505dc27/src/main/kotlin/group/infotech/drawable/dsl/drawable-dsl.kt#L31-L35

but I'm totally open for improvement suggestions

**Comment by OFmarting** [comment]
Hi,
Yes, I know that I can create the RippleDrawable directly. However, I would like to use the `maybeRipple` function to ensure that also a Drawable is provided on API Levels < 21.
